const certification_tags = {
    software_engineering: "software_engineering",
    data_science: "data_science",
    management: "management",
    blockchain: "blockchain",
    personal_development: "personal_development"
}

const CertificationData = [{
    id: 1,
    type: "Natural Language Processing",
    image: "https://s3.amazonaws.com/coursera_assets/meta_images/generated/CERTIFICATE_LANDING_PAGE/CERTIFICATE_LANDING_PAGE~2EHGKEDW3Q3V/CERTIFICATE_LANDING_PAGE~2EHGKEDW3Q3V.jpeg",
    tag: [certification_tags.data_science],
    delayAnimation: "100",
    modalDetails: [{
        certificate_name: "Natural Language Processing",
        issuing_organization: "DeepLearning.AI",
        certificate_type: "Specialization Certificate",
        tech_skills: "Python, NLTK, Scikit-learn, pandas, PyTorch, Google Colab, Word2vec, Machine Translation, Sentiment Analysis, Transformers, Attention Models",
        soft_skills: null,
        preview: "Certificate Link",
        link: "https://www.coursera.org/account/accomplishments/specialization/2EHGKEDW3Q3V",
    },],
    figure_model: {
        figure_type: 'images',
        title: 'something',
        images: ["https://s3.amazonaws.com/coursera_assets/meta_images/generated/CERTIFICATE_LANDING_PAGE/CERTIFICATE_LANDING_PAGE~2PW7KXHS86FY/CERTIFICATE_LANDING_PAGE~2PW7KXHS86FY.jpeg",
            "https://s3.amazonaws.com/coursera_assets/meta_images/generated/CERTIFICATE_LANDING_PAGE/CERTIFICATE_LANDING_PAGE~KGFVZNZ6RAE4/CERTIFICATE_LANDING_PAGE~KGFVZNZ6RAE4.jpeg",
            "https://s3.amazonaws.com/coursera_assets/meta_images/generated/CERTIFICATE_LANDING_PAGE/CERTIFICATE_LANDING_PAGE~B6BYRJZG69ZW/CERTIFICATE_LANDING_PAGE~B6BYRJZG69ZW.jpeg",
            "https://s3.amazonaws.com/coursera_assets/meta_images/generated/CERTIFICATE_LANDING_PAGE/CERTIFICATE_LANDING_PAGE~6DLG5JEP2NNQ/CERTIFICATE_LANDING_PAGE~6DLG5JEP2NNQ.jpeg"],
    },
    skills_gained: [
        "Natural Language Processing with Classification and Vector Spaces",
        "Natural Language Processing with Probabilistic Models",
        "Natural Language Processing with Sequence Models",
        "Natural Language Processing with Attention Models",
        "Use logistic regression, naïve Bayes, and word vectors to implement sentiment analysis, complete analogies & translate words",
        "Use dynamic programming, hidden Markov models, and word embeddings to implement autocorrect, autocomplete & identify part-of-speech tags for words",
        "Use recurrent neural networks, LSTMs, GRUs & Siamese networks in Trax for sentiment analysis, text generation & named entity recognition",
        "Use encoder-decoder, causal, & self-attention to machine translate complete sentences, summarize text, build chatbots & question-answering"
    ]
},
    {
        id: 2,
        type: "Deep Learning",
        image: "https://s3.amazonaws.com/coursera_assets/meta_images/generated/CERTIFICATE_LANDING_PAGE/CERTIFICATE_LANDING_PAGE~JF86GCRADY7Y/CERTIFICATE_LANDING_PAGE~JF86GCRADY7Y.jpeg",
        tag: [certification_tags.data_science],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "Deep Learning",
            issuing_organization: "DeepLearning.AI",
            certificate_type: "Specialization Certificate",
            tech_skills: "Python, Image Processing, Computer Vision, Artificial Neural Network, Convolutional Neural Network, Tensorflow, Recurrent Neural Network, Transformers, Scikit-learn, pandas, Google Colab",
            soft_skills: null,
            preview: "Certificate Link",
            link: "https://www.coursera.org/account/accomplishments/specialization/JF86GCRADY7Y",
        },],
        figure_model: {
            figure_type: 'images',
            title: 'something',
            images: [
                "https://s3.amazonaws.com/coursera_assets/meta_images/generated/CERTIFICATE_LANDING_PAGE/CERTIFICATE_LANDING_PAGE~C6KZVJK7WTHN/CERTIFICATE_LANDING_PAGE~C6KZVJK7WTHN.jpeg",
                "https://s3.amazonaws.com/coursera_assets/meta_images/generated/CERTIFICATE_LANDING_PAGE/CERTIFICATE_LANDING_PAGE~8KNSF2R64JXU/CERTIFICATE_LANDING_PAGE~8KNSF2R64JXU.jpeg",
                "https://s3.amazonaws.com/coursera_assets/meta_images/generated/CERTIFICATE_LANDING_PAGE/CERTIFICATE_LANDING_PAGE~59K4A9AQKRNF/CERTIFICATE_LANDING_PAGE~59K4A9AQKRNF.jpeg",
                "https://s3.amazonaws.com/coursera_assets/meta_images/generated/CERTIFICATE_LANDING_PAGE/CERTIFICATE_LANDING_PAGE~Z8KG7YV4KB6U/CERTIFICATE_LANDING_PAGE~Z8KG7YV4KB6U.jpeg",
                "https://s3.amazonaws.com/coursera_assets/meta_images/generated/CERTIFICATE_LANDING_PAGE/CERTIFICATE_LANDING_PAGE~YBMJFJWE86CY/CERTIFICATE_LANDING_PAGE~YBMJFJWE86CY.jpeg"],
        },
        skills_gained: [
            "Structuring Machine Learning Projects",
            "Convolutional Neural Networks",
            "Sequence Models",
            "Neural Networks and Deep Learning",
            "Improving Deep Neural Networks: Hyperparameter Tuning, Regularization and Optimization",
            "Build and train deep neural networks, identify key architecture parameters, implement vectorized neural networks and deep learning to applications",
            "Train test sets, analyze variance for DL applications, use standard techniques and optimization algorithms, and build neural networks in TensorFlow",
            "Build a CNN and apply it to detection and recognition tasks, use neural style transfer to generate art, and apply algorithms to image and video data",
            "Build and train RNNs, work with NLP and Word Embeddings, and use HuggingFace tokenizers and transformer models to perform NER and Question Answering"
        ]
    },
    {
        id: 3,
        type: "Machine Learning Operations",
        image: "https://s3.amazonaws.com/coursera_assets/meta_images/generated/CERTIFICATE_LANDING_PAGE/CERTIFICATE_LANDING_PAGE~NXBZSHPQBYQF/CERTIFICATE_LANDING_PAGE~NXBZSHPQBYQF.jpeg",
        tag: [certification_tags.data_science],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "MLOps (Machine Learning Operations) Fundamentals",
            issuing_organization: "DeepLearning.AI",
            certificate_type: "Certificate",
            tech_skills: "Python, Google CLoud, ML operation, Artificial Neural Network, Convolutional Neural Network, Tensorflow, Google Colab",
            soft_skills: null,
            preview: "Certificate Link",
            link: "https://www.coursera.org/account/accomplishments/verify/NXBZSHPQBYQF",
        },],
        figure_model: null,
        skills_gained: [
            "Identify and use core technologies required to support effective MLOps.",
            "Adopt the best CI/CD practices in the context of ML systems.",
            "Configure and provision Google Cloud architectures for reliable and effective MLOps environments.",
            "Implement reliable and repeatable training and inference workflows.",
        ]
    },
    {
        id: 4,
        type: "Data Analysis",
        image: "https://s3.amazonaws.com/coursera_assets/meta_images/generated/CERTIFICATE_LANDING_PAGE/CERTIFICATE_LANDING_PAGE~MLDHDGQV3N8D/CERTIFICATE_LANDING_PAGE~MLDHDGQV3N8D.jpeg",
        tag: [certification_tags.data_science],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "Discrete Math and Analyzing Social Graphs",
            issuing_organization: "HSE University Master of Data Science certificate program",
            certificate_type: "Certificate",
            tech_skills: "Python, NetworkX",
            soft_skills: null,
            preview: "Certificate Link",
            link: "https://www.coursera.org/account/accomplishments/verify/MLDHDGQV3N8D",
        },],
        figure_model: null,
        skills_gained: [
            "Basic Combinatorics",
            "Advanced Combinatorics",
            "Discrete Probability",
            "Introduction to Graphs",
            "Basic Graph Parameters",
            "Graphs of Social Networks"
        ]
    },
    {
        id: 5,
        type: "Data Analysis",
        image: "https://s3.amazonaws.com/coursera_assets/meta_images/generated/CERTIFICATE_LANDING_PAGE/CERTIFICATE_LANDING_PAGE~XZMX3QT79EZN/CERTIFICATE_LANDING_PAGE~XZMX3QT79EZN.jpeg",
        tag: [certification_tags.data_science],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "Principal Component Analysis with NumPy",
            issuing_organization: "Coursera",
            certificate_type: "Certificate",
            tech_skills: "Data Science, Python Programming, Seaborn, Numpy, PCA",
            soft_skills: null,
            preview: "Certificate Link",
            link: "https://www.coursera.org/account/accomplishments/verify/XZMX3QT79EZN",
        },],
        figure_model: null,
        skills_gained: [
            "Implement Principal Component Analysis (PCA) from scratch with NumPy and Python",
            "Conduct basic exploratory data analysis (EDA)",
            "Create simple data visualizations with Seaborn and Matplotlib",

        ]
    },
    {
        id: 6,
        type: "Business Analytics",
        image: "https://s3.amazonaws.com/coursera_assets/meta_images/generated/CERTIFICATE_LANDING_PAGE/CERTIFICATE_LANDING_PAGE~F8H7GMB6YLG4/CERTIFICATE_LANDING_PAGE~F8H7GMB6YLG4.jpeg",
        tag: [certification_tags.management],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "Business Analysis & Process Management",
            issuing_organization: "Coursera",
            certificate_type: "Certificate",
            tech_skills: null,
            soft_skills: "Proficient English language, Business background, Computer literacy",
            preview: "Certificate Link",
            link: "https://www.coursera.org/account/accomplishments/verify/XZMX3QT79EZN",
        },],
        figure_model: null,
        skills_gained: [
            "Analyze business processes and find solutions to existing business problems",
            "Define your business processes, their objectives and how they flow within the organizational context",
            "Evaluate the current business from a process view, break down the problems, and find an applicable business solution.",
        ]
    },
    {
        id: 7,
        type: "Agile Scrum",
        image: "https://udemy-certificate.s3.amazonaws.com/image/UC-73ef8d19-5ad2-4c0a-b870-44f37d549efc.jpg?v=1646731577000",
        tag: [certification_tags.management],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "Scrum Certification 2022\n" +
                "+ Scrum Master+ Agile Scrum\n" +
                "Training",
            issuing_organization: "Udemy",
            certificate_type: "Certificate",
            tech_skills: null,
            soft_skills: null,
            preview: "Certificate Link",
            link: "https://www.udemy.com/certificate/UC-73ef8d19-5ad2-4c0a-b870-44f37d549efc/",
        },],
        figure_model: null,
        skills_gained: [
            "Learn what scrum is and why it is so powerful for delivering even the most complex project on time.",
            "Explain what the Scrum practices are",
            "Explain the difference between Agile and Scrum",
            "Understand what Agile is & How it differs from Scrum",
            "Explain what the Waterfall Model is and Why it is less flexible than Agile",
            "Explain the difference between roles, events and artefacts"
        ]
    },
    {
        id: 8,
        type: "People Management",
        image: "https://udemy-certificate.s3.amazonaws.com/image/UC-bea135b9-60df-4729-b3b1-2aabab90fa72.jpg?v=1675520458000",
        tag: [certification_tags.management],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "Leadership: Practical Leadership Skills",
            issuing_organization: "Udemy",
            certificate_type: "Certificate",
            tech_skills: null,
            soft_skills: "Delegation, Decision Making, Critical Thinking, Monitoring",
            preview: "Certificate Link",
            link: "https://www.udemy.com/certificate/UC-bea135b9-60df-4729-b3b1-2aabab90fa72/",
        },],
        figure_model: null,
        skills_gained: [
            "Delegate effectively to empower their team",
            "Understand academic theories surrounding leadership styles and techniques",
            "Feel confident enough to involve employees in decision making and planning",
            "Know the difference between delegating styles and which one is appropriate for each situation",
            "Spend more time developing plans and ideas for the future"
        ]
    },
    {
        id: 9,
        type: "Business Administration",
        image: "https://udemy-certificate.s3.amazonaws.com/image/UC-012adc1b-ef79-470f-bf91-6c0bcf347168.jpg?v=1652642035000",
        tag: [certification_tags.management],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "An Entire MBA in 1 Course:Award Winning Business School Prof",
            issuing_organization: "Udemy",
            certificate_type: "Certificate",
            tech_skills: "Financial analysis, Venture Capital, Management Consulting, macro/micro economics, Valuation, Financial Statements",
            soft_skills: "Networking, Delegation, Decision Making, Critical Thinking, Monitoring",
            preview: "Certificate Link",
            link: "https://www.udemy.com/certificate/UC-012adc1b-ef79-470f-bf91-6c0bcf347168/",
        },],
        figure_model: null,
        skills_gained: [
            "Create financial models from scratch",
            "Analyze company financials with ease!",
            "Understand how investment banking firms work and what they can do to help your business",
            "Understand how management consulting firms work and when you need to hire them",
            "Understand how macro economics and micro economics works",
            "Understand what is venture capital and how to partner with the top venture capital firms to take your company to the next level",
            "Communicate the right way in business so that you don't waste time",
            "Network and get a meeting with anyone (ideal tips on how to get a job or how to reinvent yourself or how to find customers)",
            "Analyze entire markets and companies from a qualitative and quantitative perspective",
            "Understand how taxes work",
            "Protect your family and assets in case your business gets sued",
            "Restructure your company and the benefits of declaring bankruptcy protection if needed",
            "Partner with equity and debt providers",
            "Set up the correct and most beneficial legal entity for your company.",
        ]
    },
    {
        id: 10,
        type: "Marketing",
        image: "https://udemy-certificate.s3.amazonaws.com/image/UC-f09ad518-6f31-48ed-a43f-0da2fafe87ab.jpg?v=1666297584000",
        tag: [certification_tags.management],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "Modern Copywriting: Writing copy that sells in 2022",
            issuing_organization: "Udemy",
            certificate_type: "Certificate",
            tech_skills: "Copywriting tactics,",
            soft_skills: "Persuasion, Power Words Management",
            preview: "Certificate Link",
            link: "https://www.udemy.com/certificate/UC-f09ad518-6f31-48ed-a43f-0da2fafe87ab/",
        },],
        figure_model: null,
        skills_gained: [
            "What copywriting is and what you need to know to do it effectively",
            "How to gain a thorough understanding of your audience, competition, products, and your brand’s unique voice",
            "Copywriting tactics including structure, persuasion, emotion, power words, clarity, and more",
            "Proven copywriting formulas that remove the guesswork from writing",
            "The differences between B2B and B2C copywriting and how to craft B2B copywriting most effectively",
            "How to write headlines that draw people in and get them moving down the rest of the page",
            "Copywriting tactics for specific types of projects, including landing pages, CTAs, email, social media, videos, and much more"
        ]
    },
    {
        id: 11,
        type: "Applied Psychology",
        image: "https://udemy-certificate.s3.amazonaws.com/image/UC-cab4632f-672e-487f-9a2d-2b1893727e25.jpg?v=1673468315000",
        tag: [certification_tags.personal_development],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "Diploma in Modern Applied Psychology (DiMAP.)",
            issuing_organization: "The Academy of Modern Applied Psychology",
            certificate_type: "Certificate",
            tech_skills: null,
            soft_skills: "Communication, People Management, Persuasion, Critical Thinking, Growth Models, Goal Setting",
            preview: "Certificate Link",
            link: "https://www.udemy.com/certificate/UC-cab4632f-672e-487f-9a2d-2b1893727e25/",
        },],
        figure_model: null,
        skills_gained: [
            "Identify the motivating factors behind all patterns of human behavior",
            "Make smarter, more calculated decisions by learning from your past",
            "Use your knowledge to solve problems that directly affect people's lives",
            "Improve your ability to reason and regulate your emotional responses",
            "Make more well-informed judgments that are in line with your priorities",
            "Separate behaviour and personality from the heart of human identity",
            "Accurately predict how people will act, perceive, reason and behave",
            "Build stronger connections and more genuine relationships with people",
            "Raise your mind like a philosopher and interpret life's events accurately"
        ]
    },
    {
        id: 12,
        type: "Applied Psychology",
        image: "https://udemy-certificate.s3.amazonaws.com/image/UC-0d08e52e-8ecb-42ca-839a-fa0f236766ed.jpg?v=1659639185000",
        tag: [certification_tags.personal_development],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "Neuro-Linguistic Programming (NLP) Practitioner Certificate",
            issuing_organization: "The Academy of Modern Applied Psychology",
            certificate_type: "Certificate",
            tech_skills: null,
            soft_skills: "Communication, People Management, Persuasion, Critical Thinking, Growth Models, Goal Setting",
            preview: "Certificate Link",
            link: "https://www.udemy.com/certificate/UC-0d08e52e-8ecb-42ca-839a-fa0f236766ed/",
        },],
        figure_model: null,
        skills_gained: [
            "The conscious use of language – Milton & Meta model approaches",
            "Know how the mind works – the processes and the programming",
            "Take complete control of your thinking with the power of Anchoring",
            "Become aware of how people communicate, learn, change and develop",
            "How to formulate a vision for the future that is aligned with your values",
            "The history, study, structure and healthy presuppositions of NLP",
            "A process for setting meaningful goals and taking decisive action",
            "How to develop meaningful rapport with people and earn their trust",
            "A time-honoured framework for effective coaching and mentoring",
        ]
    },
    {
        id: 13,
        type: "Applied Psychology",
        image: "https://udemy-certificate.s3.amazonaws.com/image/UC-4bf7fb39-5c4c-4d14-902c-04159630180a.jpg?v=1663590402000",
        tag: [certification_tags.personal_development],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "NLP Master Practitioner Training (Advanced to Specialist)",
            issuing_organization: "The Academy of Modern Applied Psychology",
            certificate_type: "Certificate",
            tech_skills: null,
            soft_skills: "Communication, People Management, Persuasion, Critical Thinking, Growth Models, Goal Setting",
            preview: "Certificate Link",
            link: "https://www.udemy.com/certificate/UC-4bf7fb39-5c4c-4d14-902c-04159630180a/",
        },],
        figure_model: null,
        skills_gained: [
            "Gain a greater sense of social awareness, and improve your social skills",
            "How to communicate in a way that bypasses superficiality and falsehood",
            "A step-by-step guide to obtaining an individual's detailed personal history",
            "How values are formed, learn how to elicit, organise and reorder values",
            "Deliver captivating presentations that captivate and inspire your audience",
            "Discover how to launch and maintain a successful NLP-based enterprise",
            "Establish a clear distinction between individual identity and personality",
            "Learn how to increase your resiliency and ability to accommodate change",
            "An analysis of worldviews as a framework for understanding yourself",
        ]
    },
    {
        id: 14,
        type: "Applied Psychology",
        image: "https://udemy-certificate.s3.amazonaws.com/image/UC-c3092b38-43e9-4618-b4a3-8abb036466ca.jpg?v=1669282335000",
        tag: [certification_tags.personal_development],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "Hypnotherapy Practitioner Course (Including Demonstrations)",
            issuing_organization: "The Academy of Modern Applied Psychology",
            certificate_type: "Certificate",
            tech_skills: null,
            soft_skills: "Communication, People Management, Persuasion, Critical Thinking, Growth Models, Goal Setting",
            preview: "Certificate Link",
            link: "https://www.udemy.com/certificate/UC-c3092b38-43e9-4618-b4a3-8abb036466ca/",
        },],
        figure_model: null,
        skills_gained: [
            "The principles concerning the theory, ethics, and practice of hypnotherapy",
            "How to build collaborative relationships around clearly defined objectives",
            "Gain a greater sense of social awareness, and improve your social skills",
            "Use language patterns and hypnotic techniques to communicate efficiently",
            "A broad spectrum of relevant psychological and philosophical perspectives",
            "Understand the relationship between thoughts, emotions, and behaviours",
            "How to help individuals find emotional well-being and overcome adversity",
            "An analysis of worldviews as a basis for understanding human behaviour",
            "A broad range of easy-to-follow hypnotherapy methods and processes",
        ]
    },
    {
        id: 15,
        type: "Applied Psychology",
        image: "https://udemy-certificate.s3.amazonaws.com/image/UC-9dc5a082-283f-4481-b3de-27384d9703c9.jpg?v=1675524216000",
        tag: [certification_tags.personal_development],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "Hypnosis Practitioner & Hypnotherapy Guide (CPD Accredited)",
            issuing_organization: "Flavio Souza-Campos, Ph. D., Joeel & Natalie Rivera, Transformation Services",
            certificate_type: "Certificate",
            tech_skills: null,
            soft_skills: "Communication, People Management, Persuasion, Critical Thinking, Growth Models, Goal Setting",
            preview: "Certificate Link",
            link: "https://www.udemy.com/certificate/UC-9dc5a082-283f-4481-b3de-27384d9703c9/",
        },],
        figure_model: null,
        skills_gained: [
            "Master the fundamentals of hypnotherapy far beyond what you would if you took a conventional course",
            "Be able to hypnotize others and understand each aspect of the hypnosis process",
            "Understand and use the true power of the mind",
            "Become a highly effective listener and develop deep trust and rapport with clients",
            "Combine the skills of hypnosis with life coaching to achieve a deeper level of transformation for your clients",
            "Help clients adjust weight, quit smoking, meditate and achieve self-hypnosis",
            "Use hypnotherapy techniques to help clients access the subconscious/unconscious mind in order to create lasting change",
            "Help clients create long term goals action plans and support them by providing proven strategies and accountability",
            "Experienced professionals will appreciate the opportunity to clarify many myths"
        ]
    },
    {
        id: 16,
        type: "Cognitive Analysis & development",
        image: "https://udemy-certificate.s3.amazonaws.com/image/UC-d84b69b1-f4d9-4314-9351-5c277b8fb420.jpg?v=1670104755000",
        tag: [certification_tags.personal_development],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "Become a SuperLearner® 2: Learn Speed Reading & Boost Memory",
            issuing_organization: "Jonathan Levi, Lev Goldentouch, Anna Goldentouch, SuperHuman Academy®",
            certificate_type: "Certificate",
            tech_skills: null,
            soft_skills: "Speed Reading, Critical Thinking, Attention to Details",
            preview: "Certificate Link",
            link: "https://www.udemy.com/certificate/UC-d84b69b1-f4d9-4314-9351-5c277b8fb420/",
        },],
        figure_model: null,
        skills_gained: [
            "Learn to read roughly 3 times the speed of an average college graduate, with above-average comprehension and retention",
            "Master the exact same skills that win World Championships in Memorization - skills that can teach you to memorize thousands of data points in order",
            "Learn how to process and internalize information in a highly-effective way, and how to apply this teaching to any skill you wish to learn"
        ]
    },
    {
        id: 17,
        type: "Blockchain Foundations",
        image: "https://cdn.filestackcontent.com/11Utuof2QLKCsyUr6UYe?policy=eyJjYWxsIjpbInBpY2siLCJzdG9yZSIsInJlYWQiLCJjb252ZXJ0Iiwid3JpdGUiLCJzdGF0IiwicmVtb3ZlIl0sImV4cGlyeSI6MTY3NTUyODMxM30%3D&signature=d5e917f0ab67568f5a5ce93e77968daf3e51bd679327bc48a6d9fd42cb352d39",
        tag: [certification_tags.blockchain],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "Blockchain Foundations",
            issuing_organization: "eosio training & certification",
            certificate_type: "Certificate",
            tech_skills: "C++17, EOS.IO blockchain, wax.io",
            soft_skills: null,
            preview: "Certificate Link",
            link: "https://training.eos.io/certificates/jizn7d1lta",
        },],
        figure_model: null,
        skills_gained: [
            "Fundamentals of blockchain",
            "Consensus Protocols",
            "Smart Contract",
            "Cryptography",
            "Wallets",
            "Distributed Autonomous Organization - DAO"
        ]
    },
    {
        id: 18,
        type: "Blockchain Foundations",
        image: "https://cdn.filestackcontent.com/7872eftoRzaRh0k5ZUCk?policy=eyJjYWxsIjpbInBpY2siLCJzdG9yZSIsInJlYWQiLCJjb252ZXJ0Iiwid3JpdGUiLCJzdGF0IiwicmVtb3ZlIl0sImV4cGlyeSI6MTY3NTUyODU3MX0%3D&signature=5ad59aaa0805597ad9dfdab138ffe164da3d2dac7e91435b1a1a3944d6af046e",
        tag: [certification_tags.blockchain],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "Introduction to EOSIO - Non-technical",
            issuing_organization: "eosio training & certification",
            certificate_type: "Certificate",
            tech_skills: "C++17, EOS.IO blockchain, wax.io",
            soft_skills: null,
            preview: "Certificate Link",
            link: "https://training.eos.io/certificates/hjx0iz1gqd",
        },],
        figure_model: null,
        skills_gained: [
            "Fundamentals of EOSIO blockchain",
            "EOSIO Networks",
            "Smart Contract",
            "Cryptography",
            "Wallets",
        ]
    },
    {
        id: 19,
        type: "Blockchain Foundations",
        image: "https://cdn.filestackcontent.com/GKSXK3LTT2GFTquTAyU1?policy=eyJjYWxsIjpbInBpY2siLCJzdG9yZSIsInJlYWQiLCJjb252ZXJ0Iiwid3JpdGUiLCJzdGF0IiwicmVtb3ZlIl0sImV4cGlyeSI6MTY3NTUyODcxNn0%3D&signature=2fd8bfb7a905740d9ef14609250b7676db9ba4029bc51d63dad8f77aecdf7d94",
        tag: [certification_tags.blockchain],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "Introduction to EOSIO - Technical",
            issuing_organization: "eosio training & certification",
            certificate_type: "Certificate",
            tech_skills: "C++17, EOS.IO blockchain, wax.io",
            soft_skills: null,
            preview: "Certificate Link",
            link: "https://training.eos.io/certificates/zan28hor5r",
        },],
        figure_model: null,
        skills_gained: [
            "Models for Understanding EOSIO",
            "Resources, Accounts, and Wallets",
            "Consensus, Blocks, Transactions",
            "Deterministic WebAssembly Modules",
        ]
    },
    {
        id: 20,
        type: "Blockchain Application Development",
        image: "https://cdn.filestackcontent.com/opWc3lbTnC8oHq6V2hXt?policy=eyJjYWxsIjpbInBpY2siLCJzdG9yZSIsInJlYWQiLCJjb252ZXJ0Iiwid3JpdGUiLCJzdGF0IiwicmVtb3ZlIl0sImV4cGlyeSI6MTY3NTUyODg1OX0%3D&signature=a8f4c58fb5d9215e98775fdb6404c8b735b257dcaf8b8345ad67133013957c29",
        tag: [certification_tags.blockchain],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "Application Developer 101",
            issuing_organization: "eosio training & certification",
            certificate_type: "Certificate",
            tech_skills: "C++17, EOS.IO blockchain, wax.io",
            soft_skills: null,
            preview: "Certificate Link",
            link: "https://training.eos.io/certificates/4tu2hsktpa",
        },],
        figure_model: null,
        skills_gained: [
            "Running EOSIO Locally",
            "The Application Binary Interface (ABI)",
            "Connecting to EOSIO with the UAL",
            "Using EOSJS to Read State Tables",
            "EOSIO Testnets",
            " Potential App Improvements"
        ]
    },
    {
        id: 21,
        type: "Smart Contract Development",
        image: "https://cdn.filestackcontent.com/GZPmj3Z5R4qamdx1na6F?policy=eyJjYWxsIjpbInBpY2siLCJzdG9yZSIsInJlYWQiLCJjb252ZXJ0Iiwid3JpdGUiLCJzdGF0IiwicmVtb3ZlIl0sImV4cGlyeSI6MTY3NTUyOTAwNn0%3D&signature=768d0ceea9859a0fc3fcc1a69f02fbcb6c4d31fcdc106d13cff2f9f9e77368b5",
        tag: [certification_tags.blockchain],
        delayAnimation: "100",
        modalDetails: [{
            certificate_name: "Smart Contract 101",
            issuing_organization: "eosio training & certification",
            certificate_type: "Certificate",
            tech_skills: "C++17, EOS.IO blockchain, wax.io",
            soft_skills: null,
            preview: "Certificate Link",
            link: "https://training.eos.io/certificates/1obsfysggd",
        },],
        figure_model: null,
        skills_gained: [
            "Running EOSIO Locally",
            "Persistence with Multi-Index Tables",
            "Secondary Indices",
            "The ABI",
            "Building Out Tic Tac Toe",
            "Reading and Debugging EOSIO Code"
        ]
    }];
export default CertificationData;